version: '2.4' # Cant use 3+ because it does not support resource-limits without swarm-mode: https://github.com/docker/compose/issues/4513

services:

  mysql:
    mem_limit: ${SHIPY_STACK_SERVICE_1_MEMORY_LIMIT:-1000000000}
    build:
      context: ./
      dockerfile: Dockerfile.mysql
      args:
        VERSION: ${SHIPY_STACK_SERVICE_1_VERSION:-5}
    expose:
      - "3306"
    restart: always
    volumes:
      - mysqlconf:/etc/mysql
      - mysqldata:/var/lib/mysql
    networks:
      database:
        aliases:
         - ${COMPOSE_PROJECT_NAME:?err}
         - ${COMPOSE_PROJECT_NAME:?err}_mysql
    env_file:
      - .env
    # environment overrides env_files vars
    labels:
      # shipy labels must be present on all services
      # shipy.stack.id must be equal the name of the repository
      - "shipy.stack.id=${COMPOSE_PROJECT_NAME:?err}"
      - "shipy.stack.type=${SHIPY_STACK_TYPE:?err}"
      - "shipy.stack.name=${SHIPY_STACK_NAME:?err}"
      - "shipy.stack.domains=${SHIPY_STACK_DOMAINS:?err}"
      - "shipy.stack.updated=${SHIPY_STACK_UPDATED:?err}"
      - "shipy.stack.json=${SHIPY_STACK_JSON:?err}"
      - "shipy.stack.service.number=1"
      - "shipy.stack.service.name=mysql"
      - "shipy.stack.service.version=${SHIPY_STACK_SERVICE_1_VERSION:-5}"
    #command: --logLevel=DEBUG
    healthcheck:
      test: "/usr/bin/mysql --user=root --password=${MYSQL_ROOT_PASSWORD:?err} --execute \"SHOW DATABASES;\""
      interval: 10s
      timeout: 10s
      retries: 3
      start_period: 5s

volumes:
  mysqlconf:
  mysqldata:

networks:
  database:
      external: true
      name: database # named networks will not get removed on container update/removal
      
  
